# Generated by Django 6.0.6 on 2026-06-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='suffix',
            field=models.CharField(default='', max_length=100),
        ),
    ]
